export const predefinedKeywords = [
  "Pop",
  "Rock",
  "Hip-Hop",
  "R&B",
  "Electronic",
  "Country",
  "Indie",
  "Alternative",
  "Dance",
  "K-Pop",
  "Music Videos",
  "Live Performances",
  "Concerts",
  "Music Charts",
  "Billboard",
  "Top Hits",
  "New Releases",
  "Artist Interviews",
  "Behind the Scenes",
  "Music Awards",
  "Soundtracks",
  "Remixes",
  "Cover Songs",
  "Acoustic Sessions",
  "Lyric Videos",
  "Official Trailers",
  "Music News",
  "Album Reviews",
  "Music Tutorials",
  "Fan Reactions",
  "Exclusive Content",
  "VEVO Originals",
  "Global Music",
  "Trending Music",
  "Music Collaborations",
  "Chart Toppers",
  "Music Festivals",
  "Singer-Songwriters",
  "Band Interviews",
  "Music Production",
  "Music Industry",
  "Music Trends",
  "Viral Music",
  "Music Genres",
  "Music History",
  "Music Legends",
  "Upcoming Artists",
];
