//!
// export const allLanguage = [
//   "English",
//   "Spanish",
//   "Chinese",
//   "Hindi",
//   "Arabic",
//   "Bengali",
//   "Portuguese",
//   "Russian",
//   "Japanese",
//   "Punjabi",
//   "German",
//   "French",
//   "Korean",
//   "Turkish",
//   "Italian",
//   "Urdu",
//   "Indonesian",
//   "Dutch",
//   "Thai",
//   "Vietnamese",
//   "Swedish",
//   "Polish",
//   "Greek",
//   "Czech",
//   "Hungarian",
//   "Finnish",
//   "Romanian",
//   "Danish",
//   "Norwegian",
//   "Hebrew",
//   "Catalan",
//   "Slovak",
//   "Ukrainian",
//   "Lithuanian",
//   "Bulgarian",
//   "Croatian",
//   "Slovenian",
//   "Latvian",
//   "Estonian",
//   "Malay",
//   "Filipino",
//   "Hausa",
//   "Swahili",
//   "Yoruba",
//   "Zulu",
//   "Kurdish",
//   "Pashto",
//   "Amharic",
//   "Tigrinya",
//   "Somali",
//   "Farsi",
//   "Burmese",
//   "Khmer",
//   "Lao",
//   "Sinhala",
//   "Tamil",
//   "Telugu",
//   "Kannada",
//   "Malayalam",
//   "Marathi",
//   "Gujarati",
//   "Odia",
//   "Assamese",
//   "Maithili",
//   "Sundanese",
//   "Uzbek",
//   "Kazakh",
//   "Tajik",
//   "Kyrgyz",
//   "Turkmen",
//   "Azerbaijani",
//   "Georgian",
//   "Albanian",
//   "Serbian",
//   "Bosnian",
//   "Macedonian",
//   "Montenegrin",
//   "Belarusian",
//   "Tatar",
//   "Chechen",
//   "Avar",
//   "Dari",
//   "Balochi",
//   "Nepali",
//   "Dzongkha",
//   "Tibetan",
//   "Bhojpuri",
//   "Kinyarwanda",
//   "Kirundi",
//   "Chichewa",
//   "Oromo",
//   "Tigrinya",
//   "Sesotho",
//   "Setswana",
//   "Xhosa",
//   "Tswana",
//   "Tsonga",
//   "Venda",
//   "isiNdebele",
//   "Sesotho sa Leboa",
//   "isiZulu",
// ];
//!
export const allLanguage = [
  "Ahirani",
  "Arabic",
  "Assamese",
  "Awadhi",
  "Banjara",
  "Bengali",
  "Bhojpuri",
  "Burmese",
  "Chhattisgarhi",
  "Chinese",
  "Dogri",
  "English",
  "French",
  "Garhwali",
  "Garo",
  "Gujarati",
  "Haryanvi",
  "Himachali",
  "Hindi",
  "Iban",
  "Indonesian",
  "Italian",
  "Japanese",
  "Javanese",
  "Kannada",
  "Kashmiri",
  "Khasi",
  "Kokborok",
  "Konkani",
  "Korean",
  "Kumauni",
  "Latin",
  "Maithili",
  "Malay",
  "Malayalam",
  "Mandarin",
  "Manipuri",
  "Marathi",
  "Marwari",
  "Naga",
  "Nagpuri",
  "Nepali",
  "Odia",
  "Pali",
  "Persian",
  "Punjabi",
  "Rajasthani",
  "Sainthili",
  "Sambalpuri",
  "Sanskrit",
  "Santali",
  "Sindhi",
  "Sinhala",
  "Spanish",
  "Swahili",
  "Tamil",
  "Telugu",
  "Thai",
  "Tibetan",
  "Tulu",
  "Turkish",
  "Ukrainian",
  "Urdu",
  "zxx",
];

export const years: string[] = Array.from(new Array(50), (val, index) =>
  String(new Date().getFullYear() - index)
);
